Set default Storageclass, rewritten namespace and chart version
kubeshark/kubeshark pull request #1350
Opened 2023-04-28 14:40 UTC by GeiserX

Fixes:
- https://github.com/kubeshark/kubeshark/issues/1349
- https://github.com/kubeshark/kubeshark/issues/1348
- https://github.com/kubeshark/kubeshark/issues/1343

2023-04-28 14:46 UTC, GeiserX commented
I deleted the `00-namespace.yml` file because in Helm charts this is usually provisioned by other external means, breaking compatibility with usual tooling. Another option would be to create it depending on a value in `values.yaml`

2023-04-28 16:41 UTC, GeiserX commented
The thing is, that the `ReadWriteMany` setting on the PVC is incompatible with any of the default StorageClasses that I have in my clusters in GKE, EKS nor Rancher... This is a feature not much implemented in the principal Kubernetes providers. I would suggest rewriting the app so as to use some kind of external DB. Otherwise we will need to install NFS servers.

2023-05-01 17:53 UTC, frimik commented
On AWS EKS, *EFS* with dynamic provisioning would be required for this PV sharing to work. Having all of that in place is rather rare.

2023-05-03 21:54 UTC, mertyildiran requested changes

2023-05-03 21:54 UTC, mertyildiran commented on helm-chart/Chart.yaml
> +version: "0.1.0"
This version should match the CLI version `kubeshark version` which is `40.0` at this point.

I guess it's related to https://github.com/kubeshark/kubeshark/issues/1348

Please see the note in [here](https://github.com/kubeshark/kubeshark/wiki/CHANGELOG) to understand how we ended up with something other than SemVer. So, the repository version scheme should change for this.

2023-05-03 21:54 UTC, mertyildiran commented on helm-chart/templates/01-service-account.yaml
> +  namespace: '{{ default "kubeshark" .Release.Namespace }}'
The template files are generated automatically. So, please don't modify them directly. See the first line:

https://github.com/kubeshark/kubeshark/blob/08751add1180e7d89bada9228b059739d1e70b27/helm-chart/templates/01-service-account.yaml#L1

The correct way to modify the line is through changing this line:

https://github.com/kubeshark/kubeshark/blob/2563cc19221fb5007411613694777c0e80b717c1/cmd/helmChart.go#L116

Related to https://github.com/kubeshark/kubeshark/issues/1349

We have an existing way of configuring the Kubeshark deployment through `config.yaml` / `kubeshark.yaml` file. So, the namespace should be sourced from the `config.yaml`. [See the docs](https://docs.kubeshark.co/en/config).

2023-05-03 21:54 UTC, mertyildiran commented on helm-chart/values.yaml
> +  storageclass: ""
This file is also generated automatically and shouldn't be modified directly. The `values.yaml` should match the output of `kubeshark config` command which prints the `config.yaml`. (prints a default structure if `$HOME/.kubeshark/config.yaml` is not present)

`values.yaml` is automatically generated on these lines: https://github.com/kubeshark/kubeshark/blob/2563cc19221fb5007411613694777c0e80b717c1/cmd/helmChart.go#L350-L360

2023-05-03 23:41 UTC, mertyildiran commented on helm-chart/templates/01-service-account.yaml
> +  namespace: '{{ default "kubeshark" .Release.Namespace }}'
To clarify; we should generate such a template directive that prioritizes `.Release.Namespace` over `.Values.tap.selfnamespace`. We should also not remove `00-namespace.yaml` but instead generate such a template directive that disables `00-namespace.yaml` if `.Release.Namespace` is present or `.Values.tap.selfnamespace` is something other than `kubeshark`.

2023-07-03 18:31 UTC, mertyildiran commented
Closing in favor of current `HEAD` (dfe5605032fa34799a123ef88acd4b35b7d1399e)

2023-07-03 18:31 UTC, closed without merging