Add BFL language definition and do syntax highlighting based on that
kubeshark/kubeshark pull request #629
Opened 2022-01-12 13:28 UTC by mertyildiran

2022-01-12 13:28 UTC, mertyildiran commented
Blocked by https://github.com/uiwjs/react-textarea-code-editor/pull/85

2022-12-12 11:44 UTC, Jamiejayz13 requested changes
Thank

2022-12-12 11:44 UTC, Jamiejayz13 commented on ui-common/package-lock.json
>        "resolved": "https://registry.npmjs.org/react-toastify/-/react-toastify-8.2.0.tgz",
React

2022-12-12 11:44 UTC, Jamiejayz13 commented on ui-common/package-lock.json
> -      "integrity": "sha512-6gkSb4U6aWJB4SF2ZvLb76yCBjcvufXBqvvEx1HbmKPkutswjW1xNVRY0+daljIYRbogN7O0etYSlbiaEQyMyw==",
Integrity

2022-12-12 11:44 UTC, Jamiejayz13 commented on ui-common/package-lock.json
> +      "resolved": "https://registry.npmjs.org/rehype-prism-2/-/rehype-prism-2-0.8.1.tgz",
Resolved__

2022-12-12 12:43 UTC, mertyildiran commented
Closing since it's outdated.

2022-12-12 12:43 UTC, closed without merging